// Fill out your copyright notice in the Description page of Project Settings.


#include "AttackSpiderV2.h"

#include "AIController.h"
#include "AttackSpiderAIController.h"
#include "AttackSpider_AnimInstance.h"
#include "DeadEndingWidget.h"
#include "EngineUtils.h"
#include "SoundControlActor.h"
#include "Camera/CameraComponent.h"
#include "Components/ArrowComponent.h"
#include "Components/AudioComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SplineComponent.h"
#include "Kismet/KismetMathLibrary.h"
#include "NapolitanProject/GameFrameWork/PlayerHUD.h"
#include "NapolitanProject/GameFrameWork/TestCharacter.h"
#include "NapolitanProject/GameFrameWork/TestPlayerController.h"


// Sets default values
AAttackSpiderV2::AAttackSpiderV2()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	
	AudioComp =CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComp"));
	AudioComp->SetupAttachment(GetCapsuleComponent());
	// ëª¬ìŠ¤í„° ì¹´ë©”ë¼ ìƒì„± ë° ì´ˆê¸°í™”
	MonsterCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("MonsterCamera"));
	MonsterCamera->SetupAttachment(RootComponent); // ë£¨íŠ¸ì— ë¶€ì°©
	MonsterCamera->bUsePawnControlRotation = false; // í”Œë ˆì´ì–´ ì¡°ì‘ ë°©ì§€

	AudioComp2 =CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComp2"));
	AudioComp2->SetupAttachment(GetCapsuleComponent());
	
}

// Called when the game starts or when spawned
void AAttackSpiderV2::BeginPlay()
{
	Super::BeginPlay();

	Anim=Cast<UAttackSpider_AnimInstance>(GetMesh()->GetAnimInstance());
	
	AIController = Cast<AAttackSpiderAIController>(GetController());
	
	if (AIController)
	{
		//AIController->SetPerceptionComponent(*AIPerception);
	}
	
	TestPC=GetWorld()->GetFirstPlayerController<ATestPlayerController>();
	if (TestPC)
	{
		MainCharacter =TestPC->GetPawn<ATestCharacter>();
	}
	
	PlayerHUD =TestPC->GetHUD<APlayerHUD>();	
	if (SplineActor)
	{
		CurrentSpline=Cast<USplineComponent>(SplineActor->GetComponentByClass(USplineComponent::StaticClass()));
	}
	if (CurrentSpline==nullptr)
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("CurrentSpline Null")));
	}
	
	StartMoving();

	for (TActorIterator<ASoundControlActor> It(GetWorld(), ASoundControlActor::StaticClass()); It; ++It)
	{
		SoundControlActor = *It;
		SoundControlActor->IsSecondFloor=true; // ë¡œë¹„ì—ì„œëŠ” ë‚˜ì˜¤ëŠ” ë‹¤ë¥¸ì†Œë¦¬ì•ˆë“¤ë¦¬ë„ë¡ ì œì–´
	}
	
}

// Called every frame
void AAttackSpiderV2::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	if (bIsMoving && CurrentSpline)
	{
		MoveAlongSpline(DeltaTime);
	}

	//ê³„ì†í•´ì„œ ê±°ë¦¬ì²´í¬ë¥¼ í•˜ë©´ì„œ ê°€ê¹Œì›Œì§€ë©´ ë°°ê²½ìŒì„ ê°ì†Œì‹œí‚¤ê¸°
	//ë©€ì–´ì§€ë©´ ì¦ê°€ì‹œí‚¤ê³ 
	SoundControl();
	
}

void AAttackSpiderV2::MoveAlongSpline(float DeltaTime)
{
	if (!CurrentSpline) return;

	// ì´ë™ ê±°ë¦¬ ì¦ê°€
	DistanceAlongSpline += SplineMoveSpeed * DeltaTime;
	
	float SplineLength = CurrentSpline->GetSplineLength();

	// ğŸ¯ Spline ëì— ë„ë‹¬í•˜ë©´ ì²˜ìŒìœ¼ë¡œ ë˜ëŒë¦¬ê¸°
	if (DistanceAlongSpline >= SplineLength)
	{
		DistanceAlongSpline = 0.0f; // ğŸ¯ ë‹¤ì‹œ ì‹œì‘ì ìœ¼ë¡œ ì´ë™
	}

	// ìƒˆë¡œìš´ ìœ„ì¹˜ ë° íšŒì „ ê³„ì‚°
	FVector NewLocation = CurrentSpline->GetLocationAtDistanceAlongSpline(DistanceAlongSpline, ESplineCoordinateSpace::World);
	FRotator NewRotation = CurrentSpline->GetRotationAtDistanceAlongSpline(DistanceAlongSpline, ESplineCoordinateSpace::World);

	// ëª¬ìŠ¤í„°ë¥¼ ê±°ê¾¸ë¡œ ë§¤ë‹¬ê¸° ìœ„í•´ ì¶”ê°€ íšŒì „ ì ìš©
	NewRotation.Pitch += 180.0f; 
	NewRotation.Yaw += 180.0f; 
	SetActorLocationAndRotation(NewLocation, NewRotation);
	
}

void AAttackSpiderV2::StartMoving()
{
	if (CurrentSpline)
	{
		DistanceAlongSpline = 0.0f;
		bIsMoving = true;
	}
}

void AAttackSpiderV2::AttackPlayer()
{
	
	// ê³µê²©ì‹œì‘
	GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("ê³µê²©ì‹œì‘")));
}

void AAttackSpiderV2::DetectAndDrop()
{
	// ì†Œë¦¬
	if (DetectSound)
	{
		AudioComp->SetSound(DetectSound);
	}
	//ì›€ì§ì„ì„ ë©ˆì¶”ê³ 
	bIsMoving=false;
	//í”Œë ˆì´ì–´ë¥¼ ë³´ëŠ” ë°©í–¥ìœ¼ë¡œ íšŒì „
	FRotator LookAtRotation = UKismetMathLibrary::FindLookAtRotation(this->GetActorLocation(), MainCharacter->GetActorLocation());
	LookAtRotation.Pitch=0;
	SetActorRotation(LookAtRotation);
}

void AAttackSpiderV2::StartChasing()
{
	// í”Œë ˆì´ì–´ í–¥í•´ ì¶”ì 
	AIController->MoveToActor(MainCharacter, 5.0f);

	// 0.2ì´ˆë§ˆë‹¤ ê±°ë¦¬ ì²´í¬ (Tick ëŒ€ì‹  Timer ì‚¬ìš©)
	GetWorld()->GetTimerManager().SetTimer(ChaseCheckTimer, this, &AAttackSpiderV2::CheckAttackRange, 0.2f, true);
	
}
void AAttackSpiderV2::StartAttack()
{
	// í•œë²ˆë§Œ ì‘ë™ë˜ë„ë¡ 
	if (bAttack){return;}

	//ê³µê²©ì†Œë¦¬ë¡œ ë°”ê¾¸ê¸° 

	if (AttackSound)
	{
		AudioComp->SetSound(AttackSound);
	}
	
	MainCharacter->SetActorHiddenInGame(true);
	// í”Œë ˆì´ì–´ì´ì˜ ì´ì•ˆë³´ì´ë„ë¡ í•˜ê¸°
	TArray<AActor*> AttachedActors;
	MainCharacter->GetAttachedActors(AttachedActors);
	for (AActor* ChildActor : AttachedActors)
	{
		if (ChildActor)
		{
			ChildActor->SetActorHiddenInGame(true);
		}
	}
	// ì‚¬ë§ì´ë²¤íŠ¸ ë§Œ ë°œìƒì‹œí‚´
	MainCharacter->bIsBeingAttacked=true;
	//ì¹´ë©”ë¼ ì‰ì´í¬ .
	SwitchToMonsterCamera();
	
	// ì‚¬ë§ ë¹„ë„¤íŠ¸ íš¨ê³¼ 
	FTimerHandle UITimer2;
	GetWorld()->GetTimerManager().SetTimer(UITimer2,[this]()
	{
		if (PlayerHUD )
		{
		
			PlayerHUD->PlayDeadVignetteEffect();
		}
	},2.5f,false);
	//ì‹œê°„ì§€ì—° ì£¼ê³  ì‚¬ë§ UI ë‚˜ì˜¤ë„ë¡ 
	FTimerHandle UITimer;

	GetWorld()->GetTimerManager().SetTimer(UITimer,[this]()
	{
		MainCharacter->SetPlayerState(EPlayerState::UI);
		
		if (PlayerHUD &&PlayerHUD->DeadEndingWidgetUI)
		{
			PlayerHUD->DeadEndingWidgetUI->SetVisibility(ESlateVisibility::Visible);
			PlayerHUD->DeadEndingWidgetUI->SetTextBlock_description(description);
			//FString name= FString(TEXT("<Red_Big>ê±°ë¯¸ ì—ê²Œ</>"));
			//PlayerHUD->DeadEndingWidgetUI->SetRichText_Name(name);
			//PlayerHUD->DeadEndingWidgetUI->StartLerpTimer();
			//PlayerHUD->PlayDeadVignetteEffect();
		}
	},3.0f,false);

	bAttack=true; // í•œë²ˆë§Œ ì‘ë™ë˜ë„ë¡ ì œì–´
}

void AAttackSpiderV2::CheckAttackRange()
{
	toPlayerDistance = FVector::Distance(this->GetActorLocation(), MainCharacter->GetActorLocation());

	if (toPlayerDistance <= AttackRange)
	{
		SetAIState(EAttackSpiderV2State::Attack);
	}
	else
	{
		SetAIState(EAttackSpiderV2State::Chase);
	}
	
}


void AAttackSpiderV2::SetAIState(EAttackSpiderV2State NewState)
{
	FString message = UEnum::GetValueAsString(NewState);
	//GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Red, message);
	
	CurrentState = NewState;
	if (Anim)
	{
		Anim->CurrentState=NewState;
	}
	switch (CurrentState)
	{
	case EAttackSpiderV2State::Move:
		StartMoving();
		break;
	case EAttackSpiderV2State::Drop:
		DetectAndDrop();
		break;
	case EAttackSpiderV2State::Chase:
		StartChasing();
		break;
	case EAttackSpiderV2State::Attack:
		StartAttack();
		break;
	}
}

void AAttackSpiderV2::SoundControl()
{
	//
	if (!MainCharacter || !SoundControlActor) return;

	FVector SpiderVector=this->GetActorLocation();
	SpiderVector.Z=MainCharacter->GetActorLocation().Z;
	
	float Distance = FVector::Dist(MainCharacter->GetActorLocation(), SpiderVector);
	
	// ê±°ë¦¬ ë¹„ìœ¨ ê³„ì‚° (0 ~ 1)
	float DistanceRatio = FMath::Clamp((Distance - SoundControlMinDistance) / (SoundControlMaxDistance - SoundControlMinDistance), 0.0f, 1.0f);
    
	// **ë¹„ì„ í˜• ê°ì†Œ ì ìš© (ì œê³±)** â†’ ê°€ê¹Œìš¸ìˆ˜ë¡ ë” ê¸‰ê²©íˆ ë³¼ë¥¨ ê°ì†Œ
	float NewVolume = FMath::Clamp(FMath::Pow(DistanceRatio, 2.0f), 0.1f, 1.0f);

	// ë°°ê²½ìŒ 
	SoundControlActor->AudioComp1->SetVolumeMultiplier(NewVolume);
	
	//MainCharacter->AudioComp->SetVolumeMultiplier(1-NewVolume);
	
	if (Distance < 1000.0f) // í”Œë ˆì´ì–´ì™€ ê°€ê¹Œì›Œì§€ë©´ ë³¼ë¥¨ ê°ì†Œ
	{
		MainCharacter->PlayHeartSound();
	}
	else if (Distance > 1000.0f) // í”Œë ˆì´ì–´ê°€ ë©€ì–´ì§€ë©´ ë³¼ë¥¨ ì¦ê°€
	{
		MainCharacter->StopSound();
	}
}

void AAttackSpiderV2::SwitchToMonsterCamera()
{
	if (TestPC && MonsterCamera)
	{
		// ì¹´ë©”ë¼ ì „í™˜
		TestPC->SetViewTargetWithBlend(this, 0.1f); // 0.5ì´ˆ ë™ì•ˆ ë¶€ë“œëŸ½ê²Œ ì „í™˜

		
		// ì¹´ë©”ë¼ í”ë“¤ê¸° ì‹¤í–‰
		if (TestPC->PlayerCameraManager)
		{
			if (DeathCameraShakeClass)
			{
				TestPC->PlayerCameraManager->StartCameraShake(DeathCameraShakeClass);
				
			}
		}
	}
}



