// Fill out your copyright notice in the Description page of Project Settings.


#include "AttackSpiderAIController.h"

#include "AttackSpiderV2.h"
#include "NapolitanProject/GameFrameWork/TestCharacter.h"
#include "Perception/AIPerceptionComponent.h"
#include "Perception/AISenseConfig_Hearing.h"
#include "Perception/AISense_Hearing.h"

AAttackSpiderAIController::AAttackSpiderAIController()
{
	PrimaryActorTick.bCanEverTick = true;

	// AI PerceptionComponent ÏÉùÏÑ±
	AIPerception = CreateDefaultSubobject<UAIPerceptionComponent>(TEXT("AIPerception"));
	SetPerceptionComponent(*AIPerception);
	HearingConfig = CreateDefaultSubobject<UAISenseConfig_Hearing>(TEXT("HearingConfig"));
}

void AAttackSpiderAIController::BeginPlay()
{
	Super::BeginPlay();
	
	AttackSpider=GetPawn<AAttackSpiderV2>();
	//AttackSpider=Cast<AAttackSpiderV2>(GetPawn());
	
	if (HearingConfig)
	{
		HearingConfig->HearingRange = HearingRange_;
		HearingConfig->DetectionByAffiliation.bDetectEnemies = true;
		HearingConfig->DetectionByAffiliation.bDetectNeutrals = true;
		HearingConfig->DetectionByAffiliation.bDetectFriendlies = true;

		AIPerception->ConfigureSense(*HearingConfig);
		AIPerception->SetDominantSense(UAISense_Hearing::StaticClass());
	}
	
	AIPerception->SetSenseEnabled(UAISense_Hearing::StaticClass(),true);
	
	AIPerception->OnTargetPerceptionUpdated.AddDynamic(this, &AAttackSpiderAIController::OnTargetPerceptionUpdated);
	
}

void AAttackSpiderAIController::OnTargetPerceptionUpdated(AActor* Actor, FAIStimulus Stimulus)
{
	if (Stimulus.Type == Stimulus.SensingSucceeded)
	{
		UE_LOG(LogTemp, Warning, TEXT("üëÇ Î™¨Ïä§ÌÑ∞(AIController)Í∞Ä ÌîåÎ†àÏù¥Ïñ¥ ÏÜåÎ¶¨Î•º Í∞êÏßÄÌï®! ÏúÑÏπò: %s"),
			*Stimulus.StimulusLocation.ToString());
		if (Actor->IsA(ATestCharacter::StaticClass()))
		{
			GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("Ï∫êÎ¶≠ÌÑ∞Ïùò ÏÜåÎ¶¨Î•º Í∞êÏßÄÌï®")));

			//idleÏùºÎïåÎßå Í∞êÏßÄ
			if (AttackSpider->CurrentState==EAttackSpiderV2State::Move)
			{
				AttackSpider->SetAIState(EAttackSpiderV2State::Drop);
			}
			
		}
		
	}
	else
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("ÏÜåÎ¶¨Î•º Í∞êÏßÄÎ™ªÌï®!")));
	}
}


void AAttackSpiderAIController::OnHearNoise(const TArray<AActor*>& Actor)
{
	// Actor ÏàúÌöå .
	//GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("ÏÜåÎ¶¨Î•º Í∞êÏßÄÌï®!")));
	
	for (auto &FoundActor  :Actor)
	{
		if (FoundActor->IsA(ATestCharacter::StaticClass()))
		{
			UE_LOG(LogTemp, Warning, TEXT("ÌîåÎ†àÏù¥Ïñ¥Ïùò ÏÜåÎ¶¨Î•º Í∞êÏßÄÌï®!"));
			GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("ÌîåÎ†àÏù¥Ïñ¥Ïùò ÏÜåÎ¶¨Î•º Í∞êÏßÄÌï®!")));
			
			// ÏùºÏ†ï Í±∞Î¶¨ Ïù¥ÎÇ¥Ïù∏ÏßÄ ÌôïÏù∏
			/*float Distance = FVector::Dist(GetActorLocation(), MainCharacter->GetActorLocation());
			if (Distance <= HearingRange)
			{
				AttackPlayer();
			}*/
		}
	}
	
}