// Fill out your copyright notice in the Description page of Project Settings.


#include "Docent_JumpScare.h"

#include "DeadEndingWidget.h"
#include "Camera/CameraComponent.h"
#include "Components/AudioComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SlateWrapperTypes.h"
#include "Components/SplineComponent.h"
#include "Kismet/GameplayStatics.h"
#include "NapolitanProject/GameFrameWork/PlayerHUD.h"
#include "NapolitanProject/GameFrameWork/TestCharacter.h"
#include "NapolitanProject/GameFrameWork/TestPlayerController.h"
#include "NapolitanProject/NPC/NPC_Docent_AnimInstance.h"

// Sets default values
ADocent_JumpScare::ADocent_JumpScare()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	AudioComp =CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComp"));
	AudioComp->SetupAttachment(GetCapsuleComponent());
	// ëª¬ìŠ¤í„° ì¹´ë©”ë¼ ìƒì„± ë° ì´ˆê¸°í™”
	MonsterCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("MonsterCamera"));
	MonsterCamera->SetupAttachment(GetMesh(),FName(TEXT("HeadSocket"))); // ë£¨íŠ¸ì— ë¶€ì°©
	MonsterCamera->bUsePawnControlRotation = false; // í”Œë ˆì´ì–´ ì¡°ì‘ ë°©ì§€
}

// Called when the game starts or when spawned
void ADocent_JumpScare::BeginPlay()
{
	Super::BeginPlay();
	
	// ì²˜ìŒì—ëŠ” ì•ˆë³´ì´ë„ë¡
	SetActorHiddenInGame(true);
	
	TestPC=GetWorld()->GetFirstPlayerController<ATestPlayerController>();
	if (TestPC)
	{
		MainCharacter =TestPC->GetPawn<ATestCharacter>();
	}
	
	PlayerHUD =TestPC->GetHUD<APlayerHUD>();

	Anim=Cast<UNPC_Docent_AnimInstance>(GetMesh()->GetAnimInstance());
	
	if (SplineActor)
	{
		CurrentSpline=Cast<USplineComponent>(SplineActor->GetComponentByClass(USplineComponent::StaticClass()));
	}
	if (CurrentSpline==nullptr)
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Green, FString::Printf(TEXT("CurrentSpline Null")));
	}

	
}

// Called every frame
void ADocent_JumpScare::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	if (bIsMoving && CurrentSpline)
	{
		MoveAlongSpline(DeltaTime);
	}
}

void ADocent_JumpScare::MoveAlongSpline(float DeltaTime)
{
	if (!CurrentSpline) return;

	// ì´ë™ ê±°ë¦¬ ì¦ê°€
	DistanceAlongSpline += SplineMoveSpeed * DeltaTime;
	
	float SplineLength = CurrentSpline->GetSplineLength();

	// ğŸ¯ Spline ëì— ë„ë‹¬í•˜ë©´  => ì›€ì§ì„ ë©ˆì¶”ê³  ì í”„ìŠ¤ì¼€ì–´ ì‹œì‘í•˜ê¸° 
	if (DistanceAlongSpline >= SplineLength)
	{
		bIsMoving=false;
		// ìºë¦­í„° ì›€ì§ì´ì§€ ëª»í•˜ê²Œ í•˜ê³  ì í”„ìŠ¤ì¼€ì–´ ì‹œì‘í•˜ê¸°
		StartAttack();
	}

	// ìƒˆë¡œìš´ ìœ„ì¹˜ ë° íšŒì „ ê³„ì‚°
	FVector NewLocation = CurrentSpline->GetLocationAtDistanceAlongSpline(DistanceAlongSpline, ESplineCoordinateSpace::World);
	FRotator NewRotation = CurrentSpline->GetRotationAtDistanceAlongSpline(DistanceAlongSpline, ESplineCoordinateSpace::World);
	SetActorLocationAndRotation(NewLocation, NewRotation);
}

void ADocent_JumpScare::StartMoving()
{
	if (CurrentSpline)
	{
		DistanceAlongSpline = 0.0f;
		bIsMoving = true;
		Anim->bIsMoving=true;
	}
}

void ADocent_JumpScare::SwitchToMonsterCamera()
{
	if (TestPC && MonsterCamera)
	{
		// ì¹´ë©”ë¼ ì „í™˜
		TestPC->SetViewTargetWithBlend(this, 0.01f); // 0.5ì´ˆ ë™ì•ˆ ë¶€ë“œëŸ½ê²Œ ì „í™˜

		// ì¹´ë©”ë¼ í”ë“¤ê¸° ì‹¤í–‰
		if (TestPC->PlayerCameraManager)
		{
			if (DeathCameraShakeClass)
			{
				TestPC->PlayerCameraManager->StartCameraShake(DeathCameraShakeClass);
				
			}
		}
	}
}

void ADocent_JumpScare::StartAttack()
{
	// í•œë²ˆë§Œ ì‘ë™ë˜ë„ë¡ 
	if (bAttack){return;}

	//ê³µê²©ì†Œë¦¬ë¡œ ë°”ê¾¸ê¸°
	Anim->bIsMoving=false;
	Anim->bAttackStart=true;

	if (AttackSound)
	{
		UGameplayStatics::PlaySound2D(this, AttackSound);
	}
	
	MainCharacter->SetActorHiddenInGame(true);
	
	// ì‚¬ë§ì´ë²¤íŠ¸ ë§Œ ë°œìƒì‹œí‚´
	MainCharacter->bIsBeingAttacked=true;
	//ì¹´ë©”ë¼ ì‰ì´í¬ .

	FTimerHandle SwitchCameraTimer;

	GetWorld()->GetTimerManager().SetTimer(SwitchCameraTimer,[this]()
	{
		SwitchToMonsterCamera();
	},0.75f,false);

	
	FTimerHandle UITimer2;
	GetWorld()->GetTimerManager().SetTimer(UITimer2,[this]()
	{
		if (PlayerHUD )
		{
		
			PlayerHUD->PlayDeadVignetteEffect();
		}
	},2.5f,false);
	
	//ì‹œê°„ì§€ì—° ì£¼ê³  ì‚¬ë§ UI ë‚˜ì˜¤ë„ë¡ 
	FTimerHandle UITimer;
	GetWorld()->GetTimerManager().SetTimer(UITimer,[this]()
	{
		MainCharacter->SetPlayerState(EPlayerState::UI);
		
		if (PlayerHUD &&PlayerHUD->DeadEndingWidgetUI)
		{
			PlayerHUD->DeadEndingWidgetUI->SetVisibility(ESlateVisibility::Visible);
			PlayerHUD->DeadEndingWidgetUI->SetTextBlock_description(description);
			/*FString name= FString(TEXT("<Red_Big>ë„ìŠ¨íŠ¸ ì—ê²Œ</>"));
			PlayerHUD->DeadEndingWidgetUI->SetRichText_Name(name);
			PlayerHUD->DeadEndingWidgetUI->StartLerpTimer();*/
		}
	},3.5f,false);

	bAttack=true; // í•œë²ˆë§Œ ì‘ë™ë˜ë„ë¡ ì œì–´
}


