// Fill out your copyright notice in the Description page of Project Settings.


#include "DocentV2.h"

#include "AIController.h"
#include "EngineUtils.h"
#include "Camera/CameraComponent.h"
#include "Components/ArrowComponent.h"
#include "Components/AudioComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/Overlay.h"
#include "Components/SpotLightComponent.h"
#include "Kismet/GameplayStatics.h"
#include "NapolitanProject/GameFrameWork/PlayerHUD.h"
#include "NapolitanProject/GameFrameWork/SaveGISubsystem.h"
#include "NapolitanProject/GameFrameWork/TestCharacter.h"
#include "NapolitanProject/GameFrameWork/TestPlayerController.h"
#include "NapolitanProject/Interact/InteractWidget.h"
#include "NapolitanProject/Interact/Souvenir/Souvenir_Docent.h"
#include "NapolitanProject/YJ/DeadEndingWidget.h"
#include "NapolitanProject/YJ/SoundControlActor.h"

// Sets default values
ADocentV2::ADocentV2()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	AudioComp =CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComp"));
	AudioComp->SetupAttachment(GetCapsuleComponent());
	// ëª¬ìŠ¤í„° ì¹´ë©”ë¼ ìƒì„± ë° ì´ˆê¸°í™”
	MonsterCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("MonsterCamera"));
	MonsterCamera->SetupAttachment(GetMesh(),FName(TEXT("HeadSocket"))); // ë£¨íŠ¸ì— ë¶€ì°©
	MonsterCamera->bUsePawnControlRotation = false; // í”Œë ˆì´ì–´ ì¡°ì‘ ë°©ì§€

	//ì½œë¦°ì „ ì±„ë„
	SpotLightComp=CreateDefaultSubobject<USpotLightComponent>(TEXT("SpotLightComponent"));
	SpotLightComp->SetupAttachment(GetMesh());
}

// Called when the game starts or when spawned
void ADocentV2::BeginPlay()
{
	Super::BeginPlay();

	TestPC = GetWorld()->GetFirstPlayerController<ATestPlayerController>();
	
	if (TestPC)
	{
		MainCharacter =TestPC->GetPawn<ATestCharacter>();
	}
	
	PlayerHUD =TestPC->GetHUD<APlayerHUD>();
	
	AIController = Cast<AAIController>(GetController());

	for (TActorIterator<ASoundControlActor> It(GetWorld(), ASoundControlActor::StaticClass()); It; ++It)
	{
		SoundControlActor = *It;
	}
	//StartTurnDetect();
	SpotLightComp->SetIntensity(0.f);
}

// Called every frame
void ADocentV2::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	//DrawDebugSphere(GetWorld(), GetActorLocation(), MaxDetectionDistance, 12, FColor::Blue, false, 0.1f);

	//DrawDebugSphere(GetWorld(), GetActorLocation(), AttackRange, 12, FColor::Red, false, 0.1f);

	if (MainCharacter)
	{
		FVector CurrentLocation = MainCharacter->GetActorLocation();
	
		float DistanceToPlayer = FVector::Dist(GetActorLocation(), CurrentLocation);
		
		if (!InMaxDetectionDistance && DistanceToPlayer <= MaxDetectionDistance)
		{
			InMaxDetectionDistance=true;
			// ìŒì›ë³€ê²½
			if (SoundControlActor&&SoundControlActor->DocentBG)
			{
				SoundControlActor->BGSoundChange(SoundControlActor->DocentBG);
			}

			// ì²˜ìŒ ì§„ì… ë”±í•œë²ˆ ë§Œ .
			if (!bOnlyOnce)
			{
				// bOnlyOnce=true; //=> ì´ê±¸ ë§ˆì§€ë§‰ëŒ€ì‚¬ ëë‚ ë•Œ 
				// ëŒ€ì‚¬ë‚˜ì˜¤ë„ë¡ í•˜ê¸°
				Interact();
				// ëŒ€ì‚¬ ëë‚˜ê³  StartTurnDetect ì‹œì‘í•˜ë„ë¡ í•˜ê¸°
				// ê·¸ë¦¬ê³  ë§ˆì§€ë§‰ ëŒ€ì‚¬í• ë•Œ ì•Œì•„ì„œ ë‹«ë„ë¡ í•˜ê¸° 
			}
			else
			{
				// ì´ë•Œë¶€í„° StartTurnDetect(); ì‹œì‘í•¨
				StartTurnDetect();
			}
			
			
		}
		if (InMaxDetectionDistance&&DistanceToPlayer>MaxDetectionDistance)
		{
			InMaxDetectionDistance=false;
			// ìŒì›ë³€ê²½
			if (SoundControlActor&&SoundControlActor->LobbyRoom)
			{
				SoundControlActor->BGSoundChange(SoundControlActor->LobbyRoom);
			}
			StopAllTurnDetect();
		}
	}
	
	if (bCanDetectMovement && MainCharacter)
	{
		DetectPlayerMovement();
	}
	
	// ì¶”ì  ìƒíƒœì¼ ë•Œë§Œ ì²´í¬
	if (bHasDetectedPlayer && MainCharacter)
	{
		float Distance = FVector::Dist(GetActorLocation(), MainCharacter->GetActorLocation());

		if (Distance <= AttackRange)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ ê³µê²© ë²”ìœ„ ë„ë‹¬!"));

			// ê³µê²© ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
			PlayAttackAnimation();

			// ì´í›„ ê³„ì† ê³µê²©í•˜ì§€ ì•Šë„ë¡ ì¶”ì  ìƒíƒœ ì¢…ë£Œ
			bHasDetectedPlayer = false;

			// AI ì´ë™ë„ ë©ˆì¶¤
			if (AIController)
			{
				AIController->StopMovement();
			}
		}
	}
}




// ChoseRandomTimeTurnRightAnim ì‹œì‘ìì²´ë¥¼
void ADocentV2::StartTurnDetect()
{
	float RandValue = FMath::FRand();
	float ChosenDelay = 0.f;

	if (RandValue <= 0.6f)
	{
		ChosenDelay=FMath::FRandRange(2.0f,2.6f);
		//ChosenDelay = FMath::RandBool() ? 2.0f : 2.6f;
	}
	else
	{
		ChosenDelay = 3.0f;
	}

	UE_LOG(LogTemp, Log, TEXT("ë’¤ ëŒì•„ë³¼ë•Œê¹Œì§€ ë”œë ˆì´: %.1fì´ˆ"), ChosenDelay);


	
	GetWorldTimerManager().SetTimer(
			  PlayTurnRightAnim,
			  this,
			  &ADocentV2::PlayTurnRightAnimation,
			  ChosenDelay,
			  false
		  );
	
	
}

void ADocentV2::PlayTurnRightAnimation()
{
	
	GetMesh()->PlayAnimation(TurnAroundMontage,false);
	
	if (Souvenir_Docent)
	{
		Souvenir_Docent->ChangeCollResponseIgnore();
		UE_LOG(LogTemp, Log, TEXT("Souvenir_Docent ì½œë¦¬ì „ ìˆ˜ì •"));
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("Souvenir_Docent ì—†ìŒ"));
	}
	
	float RandValue = FMath::FRand();
	float ChosenDelay = 0.f;

	if (RandValue <= 0.6f)
	{
		ChosenDelay = 8.0f;
	}
	else
	{
		ChosenDelay = 5.0f;
	}
	
	UE_LOG(LogTemp, Log, TEXT("ì•ìœ¼ë¡œ ëŒì•„ë³¼ë•Œê¹Œì§€ ë”œë ˆì´: %.1fì´ˆ"), ChosenDelay);
	
	// 0.5ì´ˆ ì§€ë‚œí›„ ë¶€í„° í”Œë ˆì´ì–´ì˜ ì›€ì§ì„ì„ ê°ì§€
	GetWorldTimerManager().SetTimer(
		  StartDetectionTimerHandle,
		  this,
		  &ADocentV2::StartMovementDetection,
		  1.0f,
		  false
	  );
	
	// ê·¸ë¦¬ê³  ë‹¤ì‹œ ì›ë˜ëŒ€ë¡œ íšŒì „ë„ í•´ì•¼í•¨ + í”Œë ˆì´ì–´ ê°ì§€ ìŠ¤íƒ‘

	// ë°°ê²½ìŒë„ ì ì‹œ ë©ˆì¶”ê¸°
	
	GetWorld()->GetTimerManager().SetTimer(StopDetectionTimerHandle,[this]()
	{
		PlayTurnOriginAnimation();
		StopMovementDetection();
		// ë°°ê²½ìŒ ë‹¤ì‹œ í”Œë ˆì´ë˜ë„ë¡ í•˜ê¸° 
	},ChosenDelay,false);
}

void ADocentV2::PlayTurnOriginAnimation()
{
	if (TurnOriginMontage)
	{
		GetMesh()->PlayAnimation(TurnOriginMontage,false);
	}

	if (Souvenir_Docent)
	{
		Souvenir_Docent->ChangeCollResponseBlock();
	}
	
	// ë‹¤ì‹œ ì‹œì‘
	StartTurnDetect();
}

void ADocentV2::StartMovementDetection()
{
	bCanDetectMovement = true;

	// í˜„ì¬ ìœ„ì¹˜ ì €ì¥
	if (MainCharacter)
	{
		LastPlayerLocation = MainCharacter->GetActorLocation();
	}
	
	UE_LOG(LogTemp, Log, TEXT("ğŸš¨ ê°ì§€ ì‹œì‘!"));
}


void ADocentV2::DetectPlayerMovement()
{
	FVector CurrentLocation = MainCharacter->GetActorLocation();

	float DistanceToPlayer = FVector::Dist(GetActorLocation(), CurrentLocation);
	
	if (DistanceToPlayer > MaxDetectionDistance)
	{
		UE_LOG(LogTemp, Verbose, TEXT("âŒ ê°ì§€ ê±°ë¦¬ ì´ˆê³¼: %.1fcm"), DistanceToPlayer);
		return; // ë„ˆë¬´ ë©€ë©´ ê°ì§€í•˜ì§€ ì•ŠìŒ
	}
	
	// ìœ„ì¹˜ ë³€í™”ëŸ‰ ê°ì§€
	float MovementDelta = FVector::Dist(LastPlayerLocation, CurrentLocation);

	if (MovementDelta > DetectRange) // ì„ê³„ê°’ ì¡°ì • ê°€ëŠ¥
	{
		UE_LOG(LogTemp, Warning, TEXT(" í”Œë ˆì´ì–´ ì›€ì§ì„ ê°ì§€ë¨!"));

		// ê°ì§€ë˜ë©´ ì‹¤í–‰í•  í•¨ìˆ˜
		// 1. ê°ì§€ ì¤‘ì§€
		bCanDetectMovement = false;
		bHasDetectedPlayer = true;
		// 2. íƒ€ì´ë¨¸ ì·¨ì†Œ
		if (GetWorldTimerManager().IsTimerActive(StopDetectionTimerHandle))
		{
			GetWorldTimerManager().ClearTimer(StopDetectionTimerHandle);
			UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ StopDetection íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
		}

		// ë°°ê²½ìŒì€ ì¤‘ì§€í•˜ê³  , ê°ì§€ ì†Œë¦¬ ì‘ë™ì‹œí‚¤ê¸°  
		SoundControlActor->AudioComp2->Stop();
		
		if (DetectSound)
		{
			UGameplayStatics::PlaySound2D(this, DetectSound);
		}

		// íƒì§€í–ˆì„ë•Œ ì• ë‹ˆë©”ì´ì…˜ ë¨¼ì €ì‹¤í–‰
		if (DetectMontage)
		{
			GetMesh()->PlayAnimation(DetectMontage,false);
		}

		// ë‹¬ë¦¬ê¸°+ ì¶”ì ì„ ì‚´ì§ë§Œ ì§€ì—°ì‹œí‚¤ê¸°
		FTimerHandle TimerHandle;
		GetWorld()->GetTimerManager().SetTimer(TimerHandle, [this]()
		{
			if (AIController && MainCharacter)
			{
				AIController->MoveToActor(MainCharacter);
				// ë‹¬ë¦¬ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
				if (RunMontage)
				{
					GetMesh()->PlayAnimation(RunMontage,true);
				}
				UE_LOG(LogTemp, Log, TEXT("ğŸƒ ëª¬ìŠ¤í„°ê°€ í”Œë ˆì´ì–´ë¥¼ ì¶”ì  ì‹œì‘"));
			}
		}, 1.0f, false);
		
		

		// ì´í›„ ë°˜ë³µ ê°ì§€ ë§‰ê¸° ìœ„í•´ ì¢…ë£Œ
		return;
	}
	LastPlayerLocation = CurrentLocation;
}

void ADocentV2::StopMovementDetection()
{
	bCanDetectMovement = false;
	UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ ê°ì§€ ì¢…ë£Œ"));
}

void ADocentV2::PlayAttackAnimation()
{
	if (AttackMontage && !IsPlayingRootMotion()) // ì¤‘ë³µ ì¬ìƒ ë°©ì§€
	{
		PlayAnimMontage(AttackMontage);
		UE_LOG(LogTemp, Log, TEXT("ğŸ‘Š ê³µê²© ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰ë¨"));
	}

	MainCharacter->SetActorHiddenInGame(true);
	// ì‚¬ë§ì´ë²¤íŠ¸ ë§Œ ë°œìƒì‹œí‚´
	MainCharacter->bIsBeingAttacked=true;
	//ì¹´ë©”ë¼ ì‰ì´í¬ .
	SwitchToMonsterCamera();
	
	if (AttackSound)
	{
		UGameplayStatics::PlaySound2D(this, AttackSound);
	}
	

	FTimerHandle UITimer2;
	GetWorld()->GetTimerManager().SetTimer(UITimer2,[this]()
	{
		if (PlayerHUD )
		{
		
			PlayerHUD->PlayDeadVignetteEffect();
		}
	},2.5f,false);
	
	//ì‹œê°„ì§€ì—° ì£¼ê³  ì‚¬ë§ UI ë‚˜ì˜¤ë„ë¡ 
	FTimerHandle UITimer;
	GetWorld()->GetTimerManager().SetTimer(UITimer,[this]()
	{
		MainCharacter->SetPlayerState(EPlayerState::UI);
		
		if (PlayerHUD &&PlayerHUD->DeadEndingWidgetUI)
		{
			PlayerHUD->DeadEndingWidgetUI->SetVisibility(ESlateVisibility::Visible);
			PlayerHUD->DeadEndingWidgetUI->Overlay_Docent->SetVisibility(ESlateVisibility::Visible);		
			PlayerHUD->DeadEndingWidgetUI->SetTextBlock_description(description);
		}
	},3.5f,false);
}

void ADocentV2::PickUPNote()
{

	// ëª¨ë“ ê±° ë©ˆì¶”ë„ë¡ í•˜ê¸°
	StopAllTurnDetect();

	// ë„ìŠ¨íŠ¸ì˜ ì¹´ë©”ë¼ëŠ” ì œê±°í•˜ê¸°
	this->CameraComp->SetActive(false);
	this->MonsterCamera->SetActive(false);
	
	State=2;
	// ë„ìŠ¨íŠ¸ê°€ ê·¸ë¦¼ì†ì„ í–¥í•´ ì‚¬ë¼ì§€ë„ë¡ ë§Œë“¤ê¸°
	// ë¬´ì¡°ê±´ ê·¸ë¦¼ì•ì„ í–¥í•´ ë³´ê³ 
	/*UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance();
	if (AnimInstance)
	{
		UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ ë„ìŠ¨íŠ¸ì˜ AnimInstance"));

		//ëª¨ë“  ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰ ë©ˆì¶”ê³  . ê·¸ë¦¼ì†ìœ¼ë¡œ ë“¤ì–´ê°€ë„ë¡ í•˜ê³ ì‹¶ë‹¤
		
		bool bIsTurnBack=AnimInstance->Montage_IsPlaying(TurnAroundMontage);
		if (bIsTurnBack)
		{
			UE_LOG(LogTemp, Log, TEXT("ğŸ›‘TurnAround"));
			if (TurnOriginMontage)
			{
				GetMesh()->PlayAnimation(TurnOriginMontage,false);
			}
			// ì‹œê°„ì§€ì—°ì„ ì£¼ê³ 
			FTimerHandle Timer1;
			GetWorld()->GetTimerManager().SetTimer(Timer1,[this]()
			{
				if (GoingUpMontage)
				{
					GetMesh()->PlayAnimation(GoingUpMontage,true);
				}
			},3.5f,false);
			
		}
		else
		{
			//ì¡°ê¸ˆ ë†’ì´ê°€ ìˆëŠ” ê³³ìœ¼ë¡œ ê±·ëŠ” ì• ë‹ˆë©”ì´ì…˜
			// ì½”ë“œë¡œ ì•ìœ¼ë¡œ ì¡°ê¸ˆì”© ì´ë™ì‹œí‚¤ê¸° 
			if (GoingUpMontage)
			{
				GetMesh()->PlayAnimation(GoingUpMontage,true);
			}
		}
		
	}
	
	// ê·¸ë¦¬ê³  ì‹œê°„ì§€ì—° ì£¼ê³  ì‚¬ë¼ì§€ë„ë¡ í•˜ê¸°
	FTimerHandle Timer2;
	GetWorld()->GetTimerManager().SetTimer(Timer2,[this]()
	{
		Destroy();
		// ë…¸ë˜ì›ë˜ëŒ€ë¡œ ë³€ê²½í•˜ê¸°
		if (SoundControlActor&&SoundControlActor->LobbyRoom)
		{
			SoundControlActor->BGSoundChange(SoundControlActor->LobbyRoom);
		}
	},8.0f,false);*/
}

void ADocentV2::CloseUPCam()
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ADocentV2::CloseUPCam"));
	if (CheckUnderMontage)
	{
		GetMesh()->PlayAnimation(CheckUnderMontage,false);
	}
	
	this->AttachToComponent(MainCharacter->CenterArrowComp, FAttachmentTransformRules::SnapToTargetNotIncludingScale);

	// Arrowë¥¼ ë°”ë¼ë³´ë„ë¡ íšŒì „ ë³´ê°„
	FRotator DesiredRot = (MainCharacter->GetActorLocation() - this->GetActorLocation()).Rotation();
	
	this->SetActorRotation(DesiredRot);

	// ë‹¤ë¦¬ ì•ˆë³´ì´ë„ë¡ ìˆ¨ê¸°ê¸°
}

void ADocentV2::DetachDestroy()
{
	this->DetachFromActor(FDetachmentTransformRules::KeepWorldTransform);
	
	FTimerHandle Timer2;
	GetWorld()->GetTimerManager().SetTimer(Timer2,[this]()
	{
		Destroy();
		// ë…¸ë˜ì›ë˜ëŒ€ë¡œ ë³€ê²½í•˜ê¸°
		if (SoundControlActor&&SoundControlActor->LobbyRoom)
		{
			SoundControlActor->BGSoundChange(SoundControlActor->LobbyRoom);
		}
	},2.0f,false);
}

void ADocentV2::DocentLightOn()
{
	SpotLightComp->SetIntensity(LightIntensity);
}



void ADocentV2::Interact()
{
	Super::Interact();
}

int32 ADocentV2::GetNPCID()
{
	return NPC_ID;
}

int32 ADocentV2::GetState()
{
	return State;
}

void ADocentV2::SwitchToMonsterCamera()
{
	DocentLightOn();
	this->CameraComp->SetActive(false);
	this->MonsterCamera->SetActive(true);
	if (TestPC && MonsterCamera)
	{
		// ì¹´ë©”ë¼ ì „í™˜
		TestPC->SetViewTargetWithBlend(this, 0.01f); // 0.5ì´ˆ ë™ì•ˆ ë¶€ë“œëŸ½ê²Œ ì „í™˜
	}
}

void ADocentV2::StopAllTurnDetect()
{
	// íƒ€ì´ë¨¸ ì¢…ë£Œí•˜ê³  
	
	if (GetWorldTimerManager().IsTimerActive(StartDetectionTimerHandle))
	{
		GetWorldTimerManager().ClearTimer(StartDetectionTimerHandle);
		UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ StartDetectionTimerHandle íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
	}
	
	if (GetWorldTimerManager().IsTimerActive(PlayTurnRightAnim))
	{
		GetWorldTimerManager().ClearTimer(PlayTurnRightAnim);
		UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ PlayTurnRightAnim íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
	}

	
	StopMovementDetection();
}
