// Fill out your copyright notice in the Description page of Project Settings.


#include "DocentV2.h"

#include "AIController.h"
#include "EngineUtils.h"
#include "Camera/CameraComponent.h"
#include "Components/AudioComponent.h"
#include "Components/CapsuleComponent.h"
#include "Kismet/GameplayStatics.h"
#include "NapolitanProject/GameFrameWork/TestCharacter.h"
#include "NapolitanProject/GameFrameWork/TestPlayerController.h"
#include "NapolitanProject/YJ/SoundControlActor.h"

// Sets default values
ADocentV2::ADocentV2()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	AudioComp =CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComp"));
	AudioComp->SetupAttachment(GetCapsuleComponent());
	// ëª¬ìŠ¤í„° ì¹´ë©”ë¼ ìƒì„± ë° ì´ˆê¸°í™”
	MonsterCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("MonsterCamera"));
	MonsterCamera->SetupAttachment(GetMesh(),FName(TEXT("HeadSocket"))); // ë£¨íŠ¸ì— ë¶€ì°©
	MonsterCamera->bUsePawnControlRotation = false; // í”Œë ˆì´ì–´ ì¡°ì‘ ë°©ì§€
}

// Called when the game starts or when spawned
void ADocentV2::BeginPlay()
{
	Super::BeginPlay();

	TestPC = GetWorld()->GetFirstPlayerController<ATestPlayerController>();
	
	if (TestPC)
	{
		MainCharacter =TestPC->GetPawn<ATestCharacter>();
	}
	AIController = Cast<AAIController>(GetController());

	for (TActorIterator<ASoundControlActor> It(GetWorld(), ASoundControlActor::StaticClass()); It; ++It)
	{
		SoundControlActor = *It;
	}
	
	//StartTurnDetect();
}

// Called every frame
void ADocentV2::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	//DrawDebugSphere(GetWorld(), GetActorLocation(), MaxDetectionDistance, 12, FColor::Blue, false, 0.1f);

	//DrawDebugSphere(GetWorld(), GetActorLocation(), AttackRange, 12, FColor::Red, false, 0.1f);

	if (MainCharacter)
	{
		FVector CurrentLocation = MainCharacter->GetActorLocation();
	
		float DistanceToPlayer = FVector::Dist(GetActorLocation(), CurrentLocation);
		
		if (!InMaxDetectionDistance && DistanceToPlayer <= MaxDetectionDistance)
		{
			InMaxDetectionDistance=true;
			// ìŒì›ë³€ê²½
			if (SoundControlActor&&SoundControlActor->DocentBG)
			{
				SoundControlActor->BGSoundChange(SoundControlActor->DocentBG);
			}
			// ì´ë•Œë¶€í„° StartTurnDetect(); ì‹œì‘í•¨
			StartTurnDetect();
			
		}
		if (InMaxDetectionDistance&&DistanceToPlayer>MaxDetectionDistance)
		{
			InMaxDetectionDistance=false;
			// ìŒì›ë³€ê²½
			if (SoundControlActor&&SoundControlActor->LobbyRoom)
			{
				SoundControlActor->BGSoundChange(SoundControlActor->LobbyRoom);
			}
			StopAllTurnDetect();
		}
	}
	
	if (bCanDetectMovement && MainCharacter)
	{
		DetectPlayerMovement();
	}
	
	// ì¶”ì  ìƒíƒœì¼ ë•Œë§Œ ì²´í¬
	if (bHasDetectedPlayer && MainCharacter)
	{
		float Distance = FVector::Dist(GetActorLocation(), MainCharacter->GetActorLocation());

		if (Distance <= AttackRange)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ’¥ ê³µê²© ë²”ìœ„ ë„ë‹¬!"));

			// ê³µê²© ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
			PlayAttackAnimation();

			// ì´í›„ ê³„ì† ê³µê²©í•˜ì§€ ì•Šë„ë¡ ì¶”ì  ìƒíƒœ ì¢…ë£Œ
			bHasDetectedPlayer = false;

			// AI ì´ë™ë„ ë©ˆì¶¤
			if (AIController)
			{
				AIController->StopMovement();
			}
		}
	}
}




// ChoseRandomTimeTurnRightAnim ì‹œì‘ìì²´ë¥¼
void ADocentV2::StartTurnDetect()
{
	float RandValue = FMath::FRand();
	float ChosenDelay = 0.f;

	if (RandValue <= 0.6f)
	{
		ChosenDelay = 4.5f;
	}
	else
	{
		ChosenDelay = FMath::RandBool() ? 2.5f : 3.5f;
	}

	UE_LOG(LogTemp, Log, TEXT("ë’¤ ëŒì•„ë³¼ë•Œê¹Œì§€ ë”œë ˆì´: %.1fì´ˆ"), ChosenDelay);
	
	GetWorldTimerManager().SetTimer(
			  PlayTurnRightAnim,
			  this,
			  &ADocentV2::PlayTurnRightAnimation,
			  ChosenDelay,
			  false
		  );
	
	
}

void ADocentV2::PlayTurnRightAnimation()
{
	
	GetMesh()->PlayAnimation(TurnAroundMontage,false);
	
	float RandValue = FMath::FRand();
	float ChosenDelay = 0.f;

	if (RandValue <= 0.6f)
	{
		ChosenDelay = 8.0f;
	}
	else
	{
		ChosenDelay = 5.0f;
	}
	UE_LOG(LogTemp, Log, TEXT("ì•ìœ¼ë¡œ ëŒì•„ë³¼ë•Œê¹Œì§€ ë”œë ˆì´: %.1fì´ˆ"), ChosenDelay);
	
	// 0.5ì´ˆ ì§€ë‚œí›„ ë¶€í„° í”Œë ˆì´ì–´ì˜ ì›€ì§ì„ì„ ê°ì§€
	GetWorldTimerManager().SetTimer(
		  StartDetectionTimerHandle,
		  this,
		  &ADocentV2::StartMovementDetection,
		  1.5f,
		  false
	  );
	
	// ê·¸ë¦¬ê³  ë‹¤ì‹œ ì›ë˜ëŒ€ë¡œ íšŒì „ë„ í•´ì•¼í•¨ + í”Œë ˆì´ì–´ ê°ì§€ ìŠ¤íƒ‘

	GetWorld()->GetTimerManager().SetTimer(StopDetectionTimerHandle,[this]()
	{
		PlayTurnOriginAnimation();
		StopMovementDetection();
	},ChosenDelay,false);
}

void ADocentV2::PlayTurnOriginAnimation()
{
	if (TurnOriginMontage)
	{
		GetMesh()->PlayAnimation(TurnOriginMontage,false);
	}

	// ë‹¤ì‹œ ì‹œì‘
	StartTurnDetect();
}

void ADocentV2::StartMovementDetection()
{
	bCanDetectMovement = true;

	// í˜„ì¬ ìœ„ì¹˜ ì €ì¥
	if (MainCharacter)
	{
		LastPlayerLocation = MainCharacter->GetActorLocation();
	}
	
	UE_LOG(LogTemp, Log, TEXT("ğŸš¨ ê°ì§€ ì‹œì‘!"));
}


void ADocentV2::DetectPlayerMovement()
{
	FVector CurrentLocation = MainCharacter->GetActorLocation();

	float DistanceToPlayer = FVector::Dist(GetActorLocation(), CurrentLocation);
	
	if (DistanceToPlayer > MaxDetectionDistance)
	{
		UE_LOG(LogTemp, Verbose, TEXT("âŒ ê°ì§€ ê±°ë¦¬ ì´ˆê³¼: %.1fcm"), DistanceToPlayer);
		return; // ë„ˆë¬´ ë©€ë©´ ê°ì§€í•˜ì§€ ì•ŠìŒ
	}
	
	// ìœ„ì¹˜ ë³€í™”ëŸ‰ ê°ì§€
	float MovementDelta = FVector::Dist(LastPlayerLocation, CurrentLocation);

	if (MovementDelta > DetectRange) // ì„ê³„ê°’ ì¡°ì • ê°€ëŠ¥
	{
		UE_LOG(LogTemp, Warning, TEXT(" í”Œë ˆì´ì–´ ì›€ì§ì„ ê°ì§€ë¨!"));

		// ê°ì§€ë˜ë©´ ì‹¤í–‰í•  í•¨ìˆ˜
		// 1. ê°ì§€ ì¤‘ì§€
		bCanDetectMovement = false;
		bHasDetectedPlayer = true;
		// 2. íƒ€ì´ë¨¸ ì·¨ì†Œ
		if (GetWorldTimerManager().IsTimerActive(StopDetectionTimerHandle))
		{
			GetWorldTimerManager().ClearTimer(StopDetectionTimerHandle);
			UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ StopDetection íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
		}

		// ê°ì§€ ì†Œë¦¬ 
		SoundControlActor->AudioComp2->Stop();
		
		if (DetectSound)
		{
			UGameplayStatics::PlaySound2D(this, DetectSound);
		}
		
		if (AIController && MainCharacter)
		{
			AIController->MoveToActor(MainCharacter);
			// ë‹¬ë¦¬ëŠ” ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
			if (RunMontage)
			{
				GetMesh()->PlayAnimation(RunMontage,true);
			}
			UE_LOG(LogTemp, Log, TEXT("ğŸƒ ëª¬ìŠ¤í„°ê°€ í”Œë ˆì´ì–´ë¥¼ ì¶”ì  ì‹œì‘"));
		}

		// ì´í›„ ë°˜ë³µ ê°ì§€ ë§‰ê¸° ìœ„í•´ ì¢…ë£Œ
		return;
	}
	LastPlayerLocation = CurrentLocation;
}

void ADocentV2::StopMovementDetection()
{
	bCanDetectMovement = false;
	UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ ê°ì§€ ì¢…ë£Œ"));
}

void ADocentV2::PlayAttackAnimation()
{
	if (AttackMontage && !IsPlayingRootMotion()) // ì¤‘ë³µ ì¬ìƒ ë°©ì§€
	{
		PlayAnimMontage(AttackMontage);
		UE_LOG(LogTemp, Log, TEXT("ğŸ‘Š ê³µê²© ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰ë¨"));
	}

	MainCharacter->SetActorHiddenInGame(true);
	// ì‚¬ë§ì´ë²¤íŠ¸ ë§Œ ë°œìƒì‹œí‚´
	MainCharacter->bIsBeingAttacked=true;
	//ì¹´ë©”ë¼ ì‰ì´í¬ .
	SwitchToMonsterCamera();
	
	if (AttackSound)
	{
		UGameplayStatics::PlaySound2D(this, AttackSound);
	}
	/*FTimerHandle SwitchCameraTimer;
	GetWorld()->GetTimerManager().SetTimer(SwitchCameraTimer,[this]()
	{
		
	},0.75f,false);*/
}

void ADocentV2::SwitchToMonsterCamera()
{
	if (TestPC && MonsterCamera)
	{
		// ì¹´ë©”ë¼ ì „í™˜
		TestPC->SetViewTargetWithBlend(this, 0.01f); // 0.5ì´ˆ ë™ì•ˆ ë¶€ë“œëŸ½ê²Œ ì „í™˜
	}
}

void ADocentV2::StopAllTurnDetect()
{
	// íƒ€ì´ë¨¸ ì¢…ë£Œí•˜ê³  
	
	if (GetWorldTimerManager().IsTimerActive(StartDetectionTimerHandle))
	{
		GetWorldTimerManager().ClearTimer(StartDetectionTimerHandle);
		UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ StartDetectionTimerHandle íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
	}
	
	if (GetWorldTimerManager().IsTimerActive(PlayTurnRightAnim))
	{
		GetWorldTimerManager().ClearTimer(PlayTurnRightAnim);
		UE_LOG(LogTemp, Log, TEXT("ğŸ›‘ PlayTurnRightAnim íƒ€ì´ë¨¸ ì·¨ì†Œë¨"));
	}

	
	StopMovementDetection();
}
